# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 03:11
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import sizefield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_cores', models.PositiveSmallIntegerField(verbose_name='CPU Cores')),
                ('memory_size', sizefield.models.FileSizeField(help_text='Put values in MB, GB or TB. Eg.: 512MB, 1024MB, 2GB.', verbose_name='Memory size')),
                ('disk_size', sizefield.models.FileSizeField(help_text='Put values in MB, GB or TB. Eg.: 20GB, 40GB, 1TB.', verbose_name='Disk size')),
                ('disk_type', models.CharField(choices=[('ssd', 'SSD'), ('ssd', 'HDD')], default='ssd', max_length=50, verbose_name='Disk type')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=10, verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'Offers',
                'ordering': ('seller_id',),
                'verbose_name': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='OperationalSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Operational Systems',
                'ordering': ('name',),
                'verbose_name': 'Operational System',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='operational_systems',
            field=models.ManyToManyField(to='offers.OperationalSystem'),
        ),
        migrations.AddField(
            model_name='offer',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Seller'),
        ),
    ]
