# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'OS',
                'verbose_name_plural': "OS's",
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='operational_systems',
            field=models.ManyToManyField(to='offers.OperationalSystem'),
        ),
    ]
