# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:33
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20160714_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalsystem',
            options={'ordering': ('name',), 'verbose_name': 'Operational System', 'verbose_name_plural': 'Operational Systems'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
