# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20160714_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='disk_type',
            field=models.CharField(choices=[('ssd', 'SSD'), ('ssd', 'HDD')], default='ssd', max_length=50, verbose_name='Disk type'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='disk_size',
            field=models.PositiveSmallIntegerField(help_text='Put values in MB, GB or TB. Eg.: 20GB, 40GB, 1TB.', verbose_name='Disk size'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='memory_size',
            field=models.PositiveSmallIntegerField(help_text='Put values in MB, GB or TB. Eg.: 512MB, 1024MB, 2GB.', verbose_name='Memory size'),
        ),
    ]
