# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('homepage', models.URLField(help_text="Seller's homepage URL", verbose_name='Homepage')),
            ],
            options={
                'verbose_name_plural': 'Sellers',
                'verbose_name': 'Seller',
                'ordering': ('name',),
            },
        ),
    ]
